
server:
  port: ${PORT:9999}
spring:
  application:
    name: springauthserver
  jpa:
    database: sql_server
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://${HOST:};databaseName=${DB_DATABASE:};encrypt=true;trustServerCertificate=true;
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: TU_CORREO
    password: TU_CLAVE
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka}

security:
  oauth2:
    client:
      client-id: mitomediapp
      client-secret: mito89codex
      authorized-grant-types: password
      scope: read,write     