server:
  port: ${PORT:8099}
spring:
  application:
    name: springgateway
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka}

zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:  
    uaa:
      path: /uaa/**
      sensitive-headers:
      service-id: springauthserver
    mascotas:
      path: /msvc-mascotas/**
      sensitive-headers:
      service-id: msvc-mascotas
    cr:
      path: /micro-cr/**   
      sensitive-headers:   
      url: http://localhost:8081 
    nodejs:
      path: /nodejs/**         
      url: http://localhost:3000            